# build std
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

# specify no os
[build]
target = "target.json"

# automatically run in qemu
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
